### ISSUE TITLE
Foundry 0.7.4: BitD system causes an exception at startup

### ISSUE THREAD

**Issue by SolarBear** [megastruktur/foundryvtt-blades-in-the-dark#84]
I understand 0.7.4 is not supported yet, just consider this as a heads-up. :) You might already be aware of this.

Updating to 0.7.4 this morning, I ended up with the following exception while launching Foundry:

```
solarbear@candyland ~ $ node bin/foundry/resources/app/main.js 
FoundryVTT | 2020-10-17 10:48:08 | [info] Foundry Virtual Tabletop - Version 0.7.4
...
FoundryVTT | 2020-10-17 10:48:08 | [info] License verification succeeded
FoundryVTT | 2020-10-17 10:48:08 | [info] Requesting UPnP port forwarding to destination 30000
FoundryVTT | 2020-10-17 10:48:08 | [info] Server started and listening on port 30000
FoundryVTT | 2020-10-17 10:48:14 | [info] Created client session jkne4votf19cui4fs1llu7ta
(node:7513) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at /home/solarbear/bin/foundry/resources/app/dist/files/files.js:1:9531
    at Array.reduce (<anonymous>)
    at Function.getStaticFiles (/home/solarbear/bin/foundry/resources/app/dist/files/files.js:1:9283)
    at System._getStaticFiles (/home/solarbear/bin/foundry/resources/app/dist/packages/package.js:1:7834)
    at /home/solarbear/bin/foundry/resources/app/dist/packages/package.js:1:8049
    at Array.reduce (<anonymous>)
    at System._getLanguages (/home/solarbear/bin/foundry/resources/app/dist/packages/package.js:1:7987)
    at new AbstractBasePackage (/home/solarbear/bin/foundry/resources/app/dist/packages/package.js:1:3201)
(node:7513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I quickly found [a fix on Foundry's Discord](https://discord.com/channels/170995199584108546/765691837938663484/765962667721883659) and now I simply get the following error, which makes the system able to start:

```
FoundryVTT | 2020-10-17 10:50:45 | [error] Package blades-in-the-dark declares an invalid language object in its manifest file
FoundryVTT | 2020-10-17 10:50:45 | [error] Package blades-in-the-dark declares an invalid language object in its manifest file
FoundryVTT | 2020-10-17 10:50:45 | [error] Package blades-in-the-dark declares an invalid language object in its manifest file
```

I hope it helps. Thank you for your work!

**Comment by megastruktur** [comment]
Hey @SolarBear  bro, I've just checked it on a fresh 0.7.4 with installing Blades from scratch - everything works fine. Do you have the latest Blades version installed (2.4)?  :)

**Comment by SolarBear** [comment]
Huh. Strangely enough, I don't... and yet I do. It seems I have an old version but Foundry tells me there's no update to the system. I could investigate this all night oooooooorrrrrrrrrr simply remove the system and reinstall from scratch.

Nothing to see here, folks, move along! ;)
